theme: jekyll-theme-minimal

title: Social Justice Toolbox - South Asian Languages
logo: /assets/Placeholder.png
description: A community driven open source initiative to translate racial & social justice resources & terms into South Asian Languages.
